// <auto-generated />
using System;
using ContratacaoService.Adapters.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContratacaoService.Adapters.Migrations
{
    [DbContext(typeof(ContratacaoDbContext))]
    partial class ContratacaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContratacaoService.Core.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("StatusContratacao")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("ContratacaoService.Core.Domain.Entities.Contrato", b =>
                {
                    b.OwnsOne("ContratacaoService.Core.Domain.ValueObjects.ClienteContratacao", "DadosCliente", b1 =>
                        {
                            b1.Property<Guid>("ContratoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContratoId");

                            b1.ToTable("Contratos");

                            b1.WithOwner()
                                .HasForeignKey("ContratoId");
                        });

                    b.Navigation("DadosCliente")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
